# Generated by Django 5.2.8 on 2025-12-06 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_menuitem_photo_item_alter_category_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='photo_item',
            field=models.ImageField(blank=True, null=True, upload_to='store/menu_item/', verbose_name='Photo Item'),
        ),
    ]
